# Site settings
title: CeliaSiu
header-img: img/blog-header-bg.png
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/blog/" # the subpath of your site, e.g. /blog/
url: "http://csiu.github.io/" # the base hostname & protocol for your site
twitter_username: celiassiu
github_username:  csiu
stackoverflow_username: 2364901/csiu

# Build settings
markdown: kramdown
gems: [jekyll-paginate]
paginate: 5
paginate_path: "/archives/page/:num"
exclude: ["README.md", "_posts/*Rmd", "_posts/*html"]
