# Site settings
title: ReallyWhat
header-img: img/home-bg.jpg
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: celiassiu
github_username:  csiu

# Build settings
markdown: kramdown
paginate: 5
paginate_path: "/archives/page/:num"
exclude: ["README.md", "_posts/*Rmd", "_posts/*html"]
