---
title: "STAT545A enrollment"
author: "csiu"
date: "September 25, 2015"
output:
    html_document:
        keep_md: yes
---
```{r img-setup, include=FALSE, cache=FALSE}
knitr::opts_chunk$set(fig.align='center')
```

----

Currently, I'm enrolled in [STAT 545A: Exploratory Data Analysis](https://stat545-ubc.github.io), where students are introduced to data wrangling, exploration, and analysis with R. 

## The data

The instructor ([Jenny Bryan](https://twitter.com/JennyBryan)) recently compiled and made public (as a means to encourage and inspire our own data exploration) some enrollment details of students to this course.

- **[DATASET]**: [Enrollment to STAT 545A in 2015 by degree and program](https://gist.github.com/jennybc/924fe242a31e0239762f#file-2015_stat545_enrollment-csv)

```{r, echo=FALSE}
library(tidyr)
library(ggplot2)
library(grid)
library(plyr)

# setwd('_drafts/2015-09-25-stat545-enrollment/')
data <- read.delim('data/2015_STAT545_enrollment.csv', sep=",")
```

I, for one, was interested. I wanted to see what the data looks like and what stories it might reveal about my peers and I. Pictorially, the raw data looks like the following: 

```{r, echo=FALSE, dev="png", dpi=340, out.width="604px"}
databysubject <- gather(data, Program, Count, -Subject)
ggplot(subset(databysubject, subset = (databysubject$Program != "Total")),
       aes(y=Subject, x=Program, fill=Count, label=Count)) +
  geom_tile(color="grey70") +
  geom_text(color="white") +
  xlab("") +
  ylab("") +
  scale_fill_gradient(low="white", high="blue") +
  #scale_y_discrete(limits = rev(levels(data$Subject))) +
  scale_y_discrete(limits = rev(as.character(data$Subject))) +
  guides(fill=FALSE) +
  theme(panel.background = element_blank(),
        panel.border = element_blank(),
        panel.grid.major = element_blank(),
        axis.ticks.margin = unit(c(0.1,-1), 'lines'),
        axis.ticks = element_line(colour="grey90"),
        axis.text = element_text(colour="black")
        )
```

This heatmap, ordered by the total number of students per program, represents the `r sum(data$Total)` students enrolled to STAT 545A this year. It shows that most students taking this course belong to Statistics (`r sprintf('%0.1f%%', data[data$Subject == "Statistics",]$Total / sum(data$Total) * 100)`), which does not come as too much of surprise since the course (i.e. **STAT** 545A) is provided by the Department of Statistics. As a Bioinformatics student, we are representing third place (`r sprintf('%0.1f%%', data[data$Subject == "Bioinformatics",]$Total / sum(data$Total) * 100)`).

## Mostly Masters students and 2 BSc students
```{r, echo=FALSE, dev="png", dpi=140, out.width="540px"}
databyprogram <- data.frame(Count=colSums(data[,c("BSC", "Masters", "PHD")]))
ggplot(databyprogram,
       aes(x=rownames(databyprogram), y=Count, label=Count)) +
  geom_bar(stat="identity") +
  geom_text(vjust=-0.4) +
  ylim(0, 41) +
  xlab("") +
  ylab("Number of students") +
  theme(panel.grid.major.x = element_blank(),
        axis.text.y = element_blank(),
        axis.ticks.y = element_blank()
        )
```

Looking at the data differently, we see that there is twice as many Masters students than PHD students. We can also see there are 2 BSC students enrolled in this graduate course.

## The PhDs

```{r, echo=FALSE, dev="png", dpi=140, out.width="540px"}
dnormS <- with(data, 
              cbind(Subject, 
                    data[,c("BSC", "Masters", "PHD")] / Total))
ord <- hclust(dist(data.frame(dnormS[,c("BSC", "Masters", "PHD")]), 
                   method="euclidean"),
              method="ward.D")$order

datanorm <- gather(dnormS, Program, Count, -Subject)

ggplot(datanorm, aes(x=Subject, y=Count, fill=Program)) +
  geom_bar(stat="identity") + 
  scale_x_discrete(limits = as.character(data$Subject)[ord]) +
  xlab("") +
  ylab("") +
  coord_flip() #+ theme(legend.position="top")
```

Normalizing the data across subjects, we see that from Economics, Psychology, Geography, and Physics only PhD students are enrolled. 

## Other

```{r, echo=FALSE, dev="png", dpi=140, out.width="540px", fig.height=6.5}
datanormP <- t(data[,c("BSC", "Masters", "PHD")])
datanormP <- datanormP / rowSums(datanormP)

colnames(datanormP) <- data$Subject
datanormP <- data.frame(Program=rownames(datanormP), datanormP)
datanormP <- datanormP[, order(names(datanormP), decreasing=TRUE)]

datanormP <- gather(datanormP, Program)
colnames(datanormP) <- c("Program", "Subject", "Value")

ggplot(datanormP, aes(x=Program, y=Value, fill=Subject)) +
  geom_bar(stat="identity", color="black") + 
  xlab("") +
  ylab("Proportion of students") + 
  ggtitle("Enrollment to STAT 545A") +
  scale_fill_discrete(guide = guide_legend(reverse=TRUE)) +
  theme(panel.border = element_blank(),
        panel.grid.major.y = element_blank(),
        panel.grid.minor = element_blank(),
        axis.ticks.x = element_line(colour="grey90"),
        axis.ticks.y = element_blank(),
        axis.text.y = element_blank()
        )
```

----

## Past

Also provided is [STAT 545 enrollment data from the past](https://github.com/STAT545-UBC/STAT545-UBC.github.io/blob/master/course-admin/history/STAT545-registered-students-all-time-anonymized.csv)

```{r, echo=FALSE}
pastdata <- read.delim('data/STAT545-registered-students-all-time-anonymized.csv', 
                       sep=',', na.strings="")

pastdata$Program <- factor(pastdata$Program, exclude=NULL)
pastdata$year <- as.factor(pastdata$year)
```

```{r, echo=FALSE, dev="png", dpi=140, out.width="540px"}
ggplot(pastdata, aes(x=year, color=Gender)) + 
  geom_bar() + 
  xlab("") + 
  ylab("Number of enrolled students") +
  scale_color_discrete(guide = guide_legend(reverse=TRUE)) +
  theme(panel.grid.major.x = element_blank())
```

### Enrollment by gender

```{r echo=FALSE, dev="png", dpi=340, out.width="650px", fig.width=10, fig.height=7, warning=FALSE}
ggplot(pastdata, aes(x=Program, fill=Gender)) +
  geom_bar(subset=.(Gender=="Female")) +
  geom_bar(subset=.(Gender=="Male"), aes(y = ..count.. * (-1))) +
  scale_x_discrete(limits = rev(names(sort(table(pastdata$Program)))) ) + 
  scale_y_continuous(breaks=seq(-60,40,10), labels=abs(seq(-60,40,10))) +
  xlab("") +
  ylab("Enrollment by gender") +
  coord_flip() +
  theme(
    axis.text.y = element_text(colour="black")
  )
```

