---
title: "Past STAT 545A Enrollments"
author: "csiu"
date: "September 27, 2015"
output: html_document
---

## Past

Also provided is [STAT 545 enrollment data from the past](https://github.com/STAT545-UBC/STAT545-UBC.github.io/blob/master/course-admin/history/STAT545-registered-students-all-time-anonymized.csv)

```{r, echo=FALSE}
pastdata <- read.delim('data/STAT545-registered-students-all-time-anonymized.csv', 
                       sep=',', na.strings="")

pastdata$Program <- factor(pastdata$Program, exclude=NULL)
pastdata$year <- as.factor(pastdata$year)
```

```{r, echo=FALSE, dev="png", dpi=140, out.width="540px"}
ggplot(pastdata, aes(x=year, color=Gender)) + 
  geom_bar() + 
  xlab("") + 
  ylab("Number of enrolled students") +
  scale_color_discrete(guide = guide_legend(reverse=TRUE)) +
  theme(panel.grid.major.x = element_blank())
```

### Enrollment by gender

```{r echo=FALSE, dev="png", dpi=340, out.width="650px", fig.width=10, fig.height=7, warning=FALSE}
ggplot(pastdata, aes(x=Program, fill=Gender)) +
  geom_bar(subset=.(Gender=="Female")) +
  geom_bar(subset=.(Gender=="Male"), aes(y = ..count.. * (-1))) +
  scale_x_discrete(limits = rev(names(sort(table(pastdata$Program)))) ) + 
  scale_y_continuous(breaks=seq(-60,40,10), labels=abs(seq(-60,40,10))) +
  xlab("") +
  ylab("Enrollment by gender") +
  coord_flip() +
  theme(
    axis.text.y = element_text(colour="black")
  )
```

